
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from '@/components/navbar'
import Footer from "@/components/floating-dock";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en" className="dark">
      <body className={inter.className} style={{ overflowX: "hidden" }}>
        <div className="relative w-full flex justify-center items-center ">
          <Navbar />
        </div>
        {children}
        
      </body>
    </html>
  );
}
